[versions]
agp = "8.13.2"
kotlin = "2.0.21"
appcompat = "1.0.0"
material = "1.4.0"
constraintlayout = "2.1.1"
swiperefreshlayout = "1.1.0"
blockcanary = "1.5.0"
xxPermissions = "12.6"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
blockcanary-android = { group = "com.github.markzhai", name = "blockcanary-android", version.ref = "blockcanary" }
xxPermissions = { group = "com.github.getActivity", name = "XXPermissions", version.ref = "xxPermissions" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
